FROM --platform=linux/amd64 gradle:7.6.1-jdk17 AS build

WORKDIR /app
COPY . /app/
RUN gradle build --no-daemon

FROM --platform=linux/amd64 openjdk:17-slim

WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/app.jar

# Expose the port the app runs on - Cloud Run will use the PORT env variable
EXPOSE 8080

# Command to run the application with health check endpoint
CMD ["java", "-jar", "/app/app.jar"]
