name: Terraform Infrastructure

# Triggers for the workflow
on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:  # Manual trigger also enabled

env:
  PROJECT_ID: kotlin-todo-api-project
  REGION: us-central1

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="project_id=$PROJECT_ID" \
                      -var="region=$REGION" \
                      -var="db_host=${{ secrets.DB_HOST }}" \
                      -var="db_port=${{ secrets.DB_PORT }}" \
                      -var="db_name=${{ secrets.DB_NAME }}" \
                      -var="db_user=${{ secrets.DB_USER }}" \
                      -var="db_password=${{ secrets.DB_PASSWORD }}"
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve \
                      -var="project_id=$PROJECT_ID" \
                      -var="region=$REGION" \
                      -var="db_host=${{ secrets.DB_HOST }}" \
                      -var="db_port=${{ secrets.DB_PORT }}" \
                      -var="db_name=${{ secrets.DB_NAME }}" \
                      -var="db_user=${{ secrets.DB_USER }}" \
                      -var="db_password=${{ secrets.DB_PASSWORD }}"
